- name: Install PHP dependencies
  command: chdir={{ sources_directory }}/back composer install --optimize-autoloader --no-dev

- name: Build JS dependencies
  command: chdir={{ sources_directory }}/back npm install

- name: Package JS prod packages
  command: chdir={{ sources_directory }}/back npm run prod
