- name: Get environment
  shell: cp /opt/back/.env {{ sources_directory }}/back

- name: Install PHP dependencies
  command: chdir={{ sources_directory }}/back composer install --optimize-autoloader --no-dev

- name: Execute migrations
  command: chdir={{ sources_directory }}/back php artisan migrate

