- name: Install PHP dependencies
  command: chdir={{ sources_directory }}/back composer install --optimize-autoloader --no-dev

- name: Execute migrations
  command: chdir={{ sources_directory }}/back php artisan migrate

