- name: Install dependencies
  apt:
    name:
      - curl
      - nodejs
      - npm
      - unzip
      - git
      - nginx
    state: latest

- name: Install Angular
  shell: npm install -g @angular/cli

- name: Generate SSH key
  shell: >
    ssh-keygen -t rsa -f /root/.ssh/id_rsa -q -P ""

- name: Copy sources
  ansible.builtin.unarchive:
    src: frontend.zip
    dest: "{{ sources_directory }}"

- name: Copy nginx conf file
  copy:
    src=front.conf
    dest=/etc/nginx/conf.d/front.conf

- name: Set gitlab-runner permission to deploy directory
  shell: chown -R gitlab-runner /var/www

- name: Restart nginx
  shell: systemctl restart nginx

- name: Copy Gitlab-ci file
  copy:
    src=gitlab-ci.yml
    dest=/opt/front/.gitlab-ci.yml

- name: Copy Ansible playbooks
  copy:
    src=playbooks/
    dest=/opt/playbooks

- name: Add gitlab ssh key
  shell: ssh-keyscan {{ hostvars[groups['gitlab'][0]].vm_ip }} >> ~/.ssh/known_hosts
