db:
  hosts:
    T-NSA_db:
      ansible_host: 192.168.1.35
      vm_ip: 192.168.1.35
      vm_gateway: 192.168.62.1
      vm_host: t-nsa.db.local

gitlab:
  hosts:
    T_NSA-gitlab:
      ansible_host: 192.168.1.36
      vm_ip: 192.168.1.36
      vm_gateway: 192.168.62.1
      vm_host: t-nsa.gitlab.local

backend:
  hosts:
    T-NSA_backend:
      ansible_host: 192.168.62.44
      vm_ip: 192.168.62.44
      vm_gateway: 192.168.62.1
      vm_host: t-nsa.backend.local

frontend:
  hosts:
    T-NSA_frontend:
      ansible_host: 192.168.62.43
      vm_ip: 192.168.62.43
      vm_gateway: 192.168.62.1
      vm_host: t-nsa.frontend.local
