#db:
#  hosts:
#    T-NSA_db:
#      ansible_host: 192.168.62.41
#      vm_ip: 192.168.62.41
#      vm_gateway: 192.168.62.1
#      vm_host: t-nsa.db.local

#frontend:
#  hosts:
#    T-NSA_frontend:
#      ansible_host: 192.168.62.43
#      vm_ip: 192.168.62.43
#      vm_gateway: 192.168.62.1
#      vm_host: t-nsa.frontend.local

backend:
  hosts:
    T-NSA_backend:
      ansible_host: 192.168.62.44
      vm_ip: 192.168.62.44
      vm_gateway: 192.168.62.1
      vm_host: t-nsa.backend.local

gitlab:
  hosts:
    T_NSA-gitlab:
      ansible_host: 192.168.62.45
      vm_ip: 192.168.62.45
      vm_gateway: 192.168.62.1
      vm_host: t-nsa.gitlab.local
