#db:
#  hosts:
#    T-NSA_db:
#      ansible_host: 192.168.62.41
#      vm_ip: 192.168.62.41
#      vm_gateway: 192.168.62.1
#      vm_host: t-nsa.db.local

#    NSA_db_2:
#      ansible_host: 192.168.62.42
#      vm_ip: 192.168.62.42
#      vm_gateway: 192.168.62.1
#      vm_host: t-nsa.db.local

#frontend:
#  hosts:
#    frontend1:
#      ansible_host: 192.168.62.43
#      vm_frontend_ip: 192.168.62.43
#      vm_frontend_gateway: 192.168.62.1
#      vm_frontend_host: t-nsa.frontend.local
#      vm_frontend_name: T-NSA_frontend
#
#backend:
#  hosts:
#    backend1:
#      ansible_host: 192.168.62.44
#      vm_backend_ip: 192.168.62.44
#      vm_backend_gateway: 192.168.62.1
#      vm_backend_host: t-nsa.backend.local
#      vm_backend_name: T-NSA_backend
#
gitlab:
  hosts:
    T_NSA-gitlab:
      ansible_host: 192.168.62.45
      vm_ip: 192.168.62.45
      vm_gateway: 192.168.62.1
      vm_host: t-nsa.gitlab.local
