- name: Virtual machines genesis
  hosts: localhost
  connection: local

  roles:
    - genesis

- name: Gitlab configuration
  hosts: gitlab
  remote_user: root

  roles:
    - gitlab

- name: Data base configuration
  hosts: db
  remote_user: root

  roles:
    - db

- name: Backend configuration
  hosts: backend
  remote_user: root
  gather_facts: no

  roles:
    - back_config

- name: Frontend configuration
  hosts: frontend
  remote_user: root

  roles:
    - front_config
