- name: Install dependencies
  apt:
    name:
      - nodejs
      - npm
      - unzip
      - git
    state: latest

#- name: Generate SSH key
#  shell: >
#    ssh-keygen -t rsa -f /root/.ssh/id_rsa -q -P ""

#- name: Get generated SSH key
#  command: chdir=/root/.ssh cat id_rsa.pub
#  register: ssh_key

#- name: Get Gitlab API access token
#  command: chdir={{ playbook_dir }}/{{ build_directory }} cat gitlab_token.txt
#  register: gitlab_token
#  delegate_to: localhost
#
#- name: Add ssh key to Gitlab user
#  shell: >
#    curl -X POST -F "title=ssh_frontend_server" -F "key={{ ssh_key.stdout }}" http://{{ hostvars[groups['gitlab'][0]].vm_ip }}/api/v4/user/keys?access_token={{ gitlab_token.stdout }}
#  delegate_to: localhost

- name: Copy sources
  ansible.builtin.unarchive:
    src: frontend.zip
    dest: "{{ sources_directory }}"

- name: Init git repository
  command: >
    chdir={{ sources_directory }}/front git init

- name: Add remote origin to gitlab blank repository
  command: >
    chdir={{ sources_directory }}/front git remote add origin git@{{ hostvars[groups['gitlab'][0]].vm_ip }}:/root/front.git

- name: Add directory to repository
  command: >
    chdir={{ sources_directory }}/front git add .

- name: Commit
  command: >
    chdir={{ sources_directory }}/front git commit -m "first push"

- name: Push
  command: >
    chdir={{ sources_directory }}/front git push origin HEAD:master

