- name: Add gitlab-runner repository
  shell: curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh" | sudo bash

- name: Install gitlab-runner repository
  apt:
    name:
      - gitlab-runner
    state: latest

- name: Set gitlab-runner owner of project directory
  shell: chown -R gitlab-runner /var/www

- name: Set gitlab-runner owner of project directory
  shell: chown -R gitlab-runner /opt/back

- name: Add gitlab-runner to root user to run privileged commands
  lineinfile:
    path:  /etc/sudoers
    line: "gitlab-runner ALL=(ALL) NOPASSWD: /usr/bin/chown, /usr/bin/cp"
    state: present

- name: Add gitlab-runner to root user to run privileged commands
  shell: usermod -aG sudo gitlab-runner

- name: Configure gitlab runner home directory
  shell: rm /home/gitlab-runner/.bash_logout | true

- name: Get generated front repository runner token
  command: chdir={{ playbook_dir }}/{{ build_directory }} cat back_runners_token.txt
  register: runners_token
  delegate_to: localhost

- name: Register gitlab-runner with master
  command: gitlab-runner register --non-interactive --name runner --url http://"{{ hostvars[groups['gitlab'][0]].vm_ip }}" --registration-token "{{ lookup('file','{{ playbook_dir }}/{{ build_directory }}/back_runners_token.txt' ) }}" --executor shell

- name: Set permission to sources directory
  shell: chown -R gitlab-runner {{ sources_directory }}

- name: Restart runners
  command: gitlab-runner restart
