- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: Install dependencies
  become: true
  apt:
    state: latest
    name:
      - curl
      - php
      - php-cli
      - php-fpm
      - php-json
      - php-common
      - php-mysql
      - php-zip
      - php-gd
      - php-mbstring
      - php-curl
      - php-xml
      - php-pear
      - php-bcmath
      - phpunit
      - composer
      - nginx

#- name: Download Google Chrome
#  shell: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
#
#- name: Install Google Chrome
#  shell: dpkg -i google-chrome*.deb

- name: Generate SSH key
  shell: >
    ssh-keygen -t rsa -f /root/.ssh/id_rsa -q -P ""

- name: Copy sources
  ansible.builtin.unarchive:
    src: backend.zip
    dest: "{{ sources_directory }}"

- name: Copy nginx conf file
  copy:
    src=back.conf
    dest=/etc/nginx/conf.d/back.conf

- name: Restart nginx
  shell: systemctl restart nginx

- name: Copy Gitlab-ci file
  copy:
    src=gitlab-ci.yml
    dest=/opt/back/.gitlab-ci.yml

- name: Copy env file
  copy:
    src=env.conf
    dest=/opt/back/.env

- name: write env
  lineinfile:
    path: "{{sources_directory}}/back/.env"
    line: "{{item}}"
  with_items: ["DB_HOST={{hostvars[groups['db'][0]].vm_ip}}", "DB_PORT={{mysql_port}}", "DB_DATABASE={{mysql_db}}", "DB_USERNAME={{mysql_user}}", "DB_PASSWORD={{mysql_password}}"]

- name: Copy Ansible playbooks
  copy:
    src=playbooks/
    dest=/opt/playbooks

- name: Add gitlab ssh key
  shell: ssh-keyscan {{ hostvars[groups['gitlab'][0]].vm_ip }} >> ~/.ssh/known_hosts
