- name: Get environment
  shell: cp /opt/back/.env {{ sources_directory }}/back

- name: Install dependencies
  command: chdir={{ sources_directory }}/back composer install

- name: Test Laravel app
  command: chdir={{ sources_directory }}/back phpunit