- name: update os
  apt:
    name: "*"
    state: latest

- name: install common tools
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - unzip

- name: set timezone
  timezone:
    name: Europe/Paris
